### ISSUE TITLE
Hello, I can not import DiscoveryDetails as dt. 

### ISSUE THREAD

**Issue by Lpourchot** [IBM/improve-discovery-results-using-api-based-relevancy-training#4]
ModuleNotFoundError: No module named 'DiscoveryDetails

**Comment by muralidharchavan** [comment]
DiscoveryDetails.py is in the repo folder itself. Have you downloaded this file?

**Comment by muralidharchavan** [comment]
Hi Laurent. I thought this was a different issue. But realized that we spoke on slack and have fixed this issue. Hence I will close it.
