### ISSUE TITLE
Training status having "available" always false

### ISSUE THREAD

**Issue by hoavt-54** [IBM/improve-discovery-results-using-api-based-relevancy-training#7]
Hi @muralidharchavan 

I know this may not have anything to do with your code, it runs perfectly fine. But I'm wondering if you know what's wrong with this collection? The **available** status is always **false**. Please take at the CheckStatus.py output in the screenshot below.

When I update a training example, the processing status turns true for about a minute and then false again. The available status, as I said, is always "false". It has been like this for a few days.

Thank you in advance.

<img width="527" alt="Screen Shot 2022-03-01 at 11 34 16 AM" src="https://user-images.githubusercontent.com/1913161/156105465-9bd4a3f0-7c4e-4dda-916b-2e54f33331d3.png">

**Comment by muralidharchavan** [comment]
Sorry for the delayed response. I see on stackoverflow that your got this issue resolved. Hope things are working as expected now.

**Comment by hoavt-54** [comment]
@muralidharchavan thank you. Yes, I found out the [cause](https://stackoverflow.com/a/71335377/2552811).
